cmd_drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o := /mnt/nfsroot/menhui.zhang/kk-amlogic/a111/buildroot/output/host/usr/bin/arm-linux-gnueabihf-gcc -Wp,-MD,drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/.rtw_btcoex.o.d  -nostdinc -isystem /mnt/nfsroot/menhui.zhang/kk-amlogic/a111/toolchain/gcc/linux-x86/arm/gcc-linaro-arm-linux-gnueabihf-4.9/bin/../lib/gcc/arm-linux-gnueabihf/4.9.1/include -I/mnt/nfsroot/menhui.zhang/kk-amlogic/a111/buildroot/output/build/linux-custom/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/mnt/nfsroot/menhui.zhang/kk-amlogic/a111/buildroot/output/build/linux-custom/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/mnt/nfsroot/menhui.zhang/kk-amlogic/a111/buildroot/output/build/linux-custom/include/uapi -Iinclude/generated/uapi -include /mnt/nfsroot/menhui.zhang/kk-amlogic/a111/buildroot/output/build/linux-custom/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-meson8b/include -Iarch/arm/plat-meson/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror=enum-compare -Werror=comment -Werror=implicit-int -Werror=missing-braces -Werror=unused-value -Werror=format -Werror=switch -Werror=strict-prototypes -Werror=declaration-after-statement -Werror=uninitialized -Werror=unused-label -Werror=undef -Werror=unused-result -Werror=return-type -Werror=parentheses -Werror=int-to-pointer-cast -Wno-maybe-uninitialized -Wno-error=cpp -O2 -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -g -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -O1 -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -Idrivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/include -Idrivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/platform -DCONFIG_RTL8188E -DCONFIG_MP_INCLUDED -DCONFIG_POWER_SAVING -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DCONFIG_LITTLE_ENDIAN  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rtw_btcoex)"  -D"KBUILD_MODNAME=KBUILD_STR(8188eu)" -c -o drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.c

source_drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o := drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.c

deps_drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o := \
    $(wildcard include/config/bt/coexist.h) \
    $(wildcard include/config/concurrent/mode.h) \
    $(wildcard include/config/error/reset.h) \

drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o: $(deps_drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o)

$(deps_drivers/amlogic/../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/core/rtw_btcoex.o):
